apiVersion: v1
kind: Service
metadata:
  name: skyblock-server
  namespace: skyblock-server
  labels:
    app: skyblock-server
spec:
  type: NodePort
  ports:
    - port: 25565
      nodePort: 30565
  selector:
    app: skyblock-server
